### PR TITLE
Support NULL option parmeter

### PR DESCRIPTION
**Pull request by xorphitus**
I think that the NULL option parameter is useful for using COPY FROM command.
So add an option to `copy_from` method for it.

### CODE REVIEW

**Comment by diogob** [comment]
Thanks for the PR :D 
Could you add some test coverage for this use case?

**Comment by xorphitus** [comment]
Sure. Please wait for a while.

**Comment by xorphitus** [comment]
I added 2 test cases.
Please confirm them.

**Comment by diogob** [comment]
@xorphitus thanks for the PR. I'm merging this and releasing a minor version

**Pull request merged**
